language: python
sudo: true
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - "virtualenv venv --no-site-packages"
  - "source venv/bin/activate"
  - pip install --upgrade pip setuptools
  - pip install pytest --upgrade
  - pip install pytest-cov --upgrade
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test  --cov=./
after_success:
  - codecov
before_deploy:
  - pip install twine
deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  skip_existing: true
  on:
    tags: true
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never

